#!/usr/bin/env perl

use v5.10.0;
use strict;
use warnings;

$|++;

my @lines = (
'checking for inttypes.h... yes', # 125
'checking for stdint.h... yes', # 123
'checking for a BSD-compatible install... /usr/bin/install -c', # 121
'checking for gawk... gawk', # 117
'checking whether we are cross compiling... no', # 115
'checking whether gcc accepts -g... yes', # 115
'checking for egrep... /bin/grep -E', # 115
'checking whether we are using the GNU C compiler... yes', # 114
'checking whether the C compiler works... yes', # 114
'checking for unistd.h... yes', # 114
'checking for suffix of executables... ', # 114
'checking for string.h... yes', # 114
'checking for stdlib.h... yes', # 114
'checking for gcc... gcc', # 114
'checking for ANSI C header files... yes', # 114
'checking whether make sets $(MAKE)... yes', # 113
'checking host system type... i686-pc-linux-gnu', # 113
'checking for sys/types.h... yes', # 113
'checking for sys/stat.h... yes', # 113
'checking for suffix of object files... o', # 113
'checking for strings.h... yes', # 113
'checking for memory.h... yes', # 113
'checking for C compiler default output file name... a.out', # 113
'checking build system type... i686-pc-linux-gnu', # 113
'checking for grep that handles long lines and -e... /bin/grep', # 112
'checking for gcc option to accept ISO C89... none needed', # 112
'checking for a thread-safe mkdir -p... /bin/mkdir -p', # 108
'checking whether build environment is sane... yes', # 107
'checking for a sed that does not truncate output... /bin/sed', # 97
'checking for style of include used by make... GNU', # 95
'checking how to run the C preprocessor... gcc -E', # 92
'checking how to hardcode library paths into programs... immediate', # 92
'checking whether ln -s works... yes', # 88
'checking for ranlib... ranlib', # 83
'checking for ar... ar', # 79
'checking dependency style of gcc... gcc3', # 75
'checking for dlfcn.h... yes', # 73
'checking if libtool supports shared libraries... yes', # 72
'checking for strip... strip', # 72
'checking whether to build shared libraries... yes', # 71
'checking whether stripping libraries is possible... yes', # 70
'checking for fgrep... /bin/grep -F', # 70
'checking the maximum length of command line arguments... 1572864', # 69
'checking how to recognize dependent libraries... pass_all', # 69
'checking for objdump... objdump', # 69
'checking for objdir... .libs', # 69
'checking dynamic linker characteristics... GNU/Linux ld.so', # 69
'checking whether -lc should be explicitly linked in... no', # 68
'checking how to print strings... printf', # 67
'checking pkg-config is at least version 0.9.0... yes', # 65
'checking if gcc supports -c -o file.o... (cached) yes', # 65
'checking for unistd.h... (cached) yes', # 65
'checking for sysroot... no', # 65
'checking for mt... no', # 65
'checking whether the shell understands \'+=\'... yes', # 64
'checking whether the shell understands some XSI constructs... yes', # 64
'checking if : is a manifest tool... no', # 64
'checking how to convert i686-pc-linux-gnu file names to toolchain format... func_convert_file_noop', # 64
'checking how to convert i686-pc-linux-gnu file names to i686-pc-linux-gnu format... func_convert_file_noop', # 64
'checking how to associate runtime and link libraries... printf %s\n', # 64
'checking for archiver @FILE support... @', # 64
'checking whether to build static libraries... yes', # 63
'checking if gcc supports -fno-rtti -fno-exceptions... no', # 63
'checking if gcc supports -c -o file.o... yes', # 63
'checking if gcc static flag -static works... yes', # 63
'checking if gcc PIC flag -fPIC -DPIC works... yes', # 63
'checking for gcc option to produce PIC... -fPIC -DPIC', # 63
'checking for dlltool... no', # 56
'checking whether to enable maintainer-specific portions of Makefiles... no', # 52
'checking for stdint.h... (cached) yes', # 46
'checking for gcc option to accept ISO C99... -std=gnu99', # 45
'checking for stdlib.h... (cached) yes', # 43
'checking for size_t... yes', # 43
'checking for sys/types.h... (cached) yes', # 40
'checking whether make supports nested variables... yes', # 38
'checking for an ANSI C-conforming const... yes', # 35
'checking whether it is safe to define __EXTENSIONS__... yes', # 33
'checking minix/config.h usability... no', # 33
'checking minix/config.h presence... no', # 33
'checking for special C compiler options needed for large files... no', # 33
'checking for minix/config.h... no', # 33
'checking for _FILE_OFFSET_BITS value needed for large files... 64', # 33
'checking for ANSI C header files... (cached) yes', # 33
'checking whether we are using the GNU C compiler... (cached) yes', # 31
'checking whether gcc accepts -g... (cached) yes', # 31
'checking for gcc option to accept ISO C89... (cached) none needed', # 30
'checking for gcc... (cached) gcc', # 30
'checking for sys/time.h... yes', # 29
'checking for sys/param.h... yes', # 28
'checking for fcntl.h... yes', # 28
'checking for inttypes.h... (cached) yes', # 27
'checking how to run the C preprocessor... gcc -std=gnu99 -E', # 26
'checking for string.h... (cached) yes', # 26
'checking fcntl.h usability... yes', # 26
'checking fcntl.h presence... yes', # 26
'checking whether __SUNPRO_C is declared... no', # 25
'checking whether __INTEL_COMPILER is declared... no', # 25
'checking whether __clang__ is declared... no', # 25
'checking that generated files are newer than configure... done', # 25
'checking dependency style of gcc... none', # 25
'checking sys/time.h usability... yes', # 24
'checking sys/time.h presence... yes', # 24
'checking for sys/select.h... yes', # 23
'checking for pid_t... yes', # 23
'checking whether byte ordering is bigendian... no', # 22
'checking for perl... /usr/local/bin/perl', # 22
'checking for MAP_ANONYMOUS... yes', # 22
'checking whether we are using the GNU C++ compiler... yes', # 21
'checking for xsltproc... /usr/bin/xsltproc', # 21
'checking for snprintf... yes', # 21
'checking for setlocale... yes', # 21
'checking for limits.h... yes', # 21
'checking for inline... inline', # 21
'checking for g++... g++', # 21
'checking for getpagesize... yes', # 21
'checking dynamic linker characteristics... (cached) GNU/Linux ld.so', # 21
'checking dependency style of gcc... (cached) gcc3', # 21
'checking whether make sets $(MAKE)... (cached) yes', # 20
'checking whether g++ accepts -g... yes', # 20
'checking for strdup... yes', # 20
'checking for gettimeofday... yes', # 20
'checking for a traditional french locale... (cached) none', # 20
'checking for a french Unicode locale... (cached) none', # 20
'checking sys/select.h usability... yes', # 19
'checking sys/select.h presence... yes', # 19
'checking limits.h usability... yes', # 19
'checking limits.h presence... yes', # 19
'checking for sys/stat.h... (cached) yes', # 19
'checking for mmap... (cached) yes', # 19
'checking for malloc.h... yes', # 19
'checking for dlopen in -ldl... yes', # 19
'checking whether NLS is requested... yes', # 18
'checking whether gcc understands -c and -o together... yes', # 18
'checking how to run the C++ preprocessor... g++ -E', # 18
'checking for xgettext... /usr/bin/xgettext', # 18
'checking for sys/socket.h... yes', # 18
'checking for msgfmt... /usr/bin/msgfmt', # 18
'checking for gmsgfmt... /usr/bin/gmsgfmt', # 18
'checking for gawk... (cached) gawk', # 18
'checking for dirent.h that defines DIR... yes', # 18
'checking dependency style of g++... gcc3', # 18
'checking whether time.h and sys/time.h may both be included... yes', # 17
'checking size of long... 4', # 17
'checking malloc.h usability... yes', # 17
'checking malloc.h presence... yes', # 17
'checking if g++ supports -c -o file.o... yes', # 17
'checking if g++ supports -c -o file.o... (cached) yes', # 17
'checking if g++ static flag -static works... yes', # 17
'checking if g++ PIC flag -fPIC -DPIC works... yes', # 17
'checking if gcc -std=gnu99 supports -Werror=unused-command-line-argument... no', # 17
'checking if gcc -std=gnu99 supports -Werror=unknown-warning-option... no', # 17
'checking for working alloca.h... yes', # 17
'checking for strings.h... (cached) yes', # 17
'checking for strcasecmp... yes', # 17
'checking for library containing opendir... none required', # 17
'checking for g++ option to produce PIC... -fPIC -DPIC', # 17
'checking for alloca... yes', # 17
'checking for shared library run path origin... done', # 16
'checking for off_t... yes', # 16
'checking for msgmerge... /usr/bin/msgmerge', # 16
'checking for memmove... yes', # 16
'checking the xmlto version... 0.0.24', # 15
'checking size of int... 4', # 15
'checking for xmlto... /usr/bin/xmlto', # 15
'checking for utime.h... yes', # 15
'checking for sys/wait.h... yes', # 15
'checking for socklen_t... yes', # 15
'checking for setenv... yes', # 15
'checking for mmap... yes', # 15
'checking for locale.h... yes', # 15
'checking for fop... no', # 15
'checking whether to use NLS... yes', # 14
'checking where the gettext function comes from... libc', # 14
'checking sys/param.h usability... yes', # 14
'checking sys/param.h presence... yes', # 14
'checking for uid_t in sys/types.h... yes', # 14
'checking for termios.h... yes', # 14
'checking for sys/mman.h... yes', # 14
'checking for ssize_t... yes', # 14
'checking for nl_langinfo and CODESET... yes', # 14
'checking for mode_t... yes', # 14
'checking for lstat... yes', # 14
'checking for GNU gettext in libc... yes', # 14
'checking for getopt.h... yes', # 14
'checking for getcwd... yes', # 14
'checking for getaddrinfo... yes', # 14
'checking for dirent.h... yes', # 14
'checking for CFPreferencesCopyAppValue... no', # 14
'checking for CFLocaleCopyCurrent... no', # 14
'checking utime.h usability... yes', # 13
'checking utime.h presence... yes', # 13
'checking return type of signal handlers... void', # 13
'checking locale.h usability... yes', # 13
'checking locale.h presence... yes', # 13
'checking for X.Org SGML entities >= 1.8... no', # 13
'checking for working mmap... yes', # 13
'checking for vsnprintf... yes', # 13
'checking for sys/ioctl.h... yes', # 13
'checking whether to build functional specifications... yes', # 12
'checking whether struct tm is in sys/time.h or time.h... time.h', # 12
'checking whether mbrtowc works as well as mbtowc... (cached) guessing yes', # 12
'checking whether mbrtowc handles incomplete characters... (cached) guessing yes', # 12
'checking whether make supports nested variables... (cached) yes', # 12
'checking sys/wait.h usability... yes', # 12
'checking sys/wait.h presence... yes', # 12
'checking sys/socket.h usability... yes', # 12
'checking sys/socket.h presence... yes', # 12
'checking sys/file.h usability... yes', # 12
'checking sys/file.h presence... yes', # 12
'checking size of short... 2', # 12
'checking pthread.h usability... yes', # 12
'checking pthread.h presence... yes', # 12
'checking if gcc -std=gnu99 supports -Wunused... yes', # 12
'checking if gcc -std=gnu99 supports -Wuninitialized... yes', # 12
'checking if gcc -std=gnu99 supports -Wstrict-prototypes... yes', # 12
'checking if gcc -std=gnu99 supports -Wpointer-arith... yes', # 12
'checking if gcc -std=gnu99 supports -Wold-style-definition... yes', # 12
'checking if gcc -std=gnu99 supports -Wnested-externs... yes', # 12
'checking if gcc -std=gnu99 supports -Wmissing-prototypes... yes', # 12
'checking if gcc -std=gnu99 supports -Wmissing-declarations... yes', # 12
'checking if gcc -std=gnu99 supports -Wformat=2... yes', # 12
'checking if gcc -std=gnu99 supports -Wdeclaration-after-statement... yes', # 12
'checking if gcc -std=gnu99 supports -Wall... yes', # 12
'checking for sys/socket.h... (cached) yes', # 12
'checking for sys/resource.h... yes', # 12
'checking for sys/file.h... yes', # 12
'checking for symlink... yes', # 12
'checking for strerror... yes', # 12
'checking for ptrdiff_t... yes', # 12
'checking for pthread.h... yes', # 12
'checking for errno.h... yes', # 12
'checking for a transitional chinese locale... (cached) none', # 12
'checking for a traditional japanese locale... (cached) none', # 12
'checking termios.h usability... yes', # 11
'checking termios.h presence... yes', # 11
'checking sys/resource.h usability... yes', # 11
'checking sys/resource.h presence... yes', # 11
'checking sys/mman.h usability... yes', # 11
'checking sys/mman.h presence... yes', # 11
'checking stddef.h usability... yes', # 11
'checking stddef.h presence... yes', # 11
'checking size of long long... 8', # 11
'checking if gcc -std=gnu99 supports -Wshadow... yes', # 11
'checking if gcc -std=gnu99 supports -Wredundant-decls... yes', # 11
'checking if gcc -std=gnu99 supports -Wmissing-noreturn... yes', # 11
'checking if gcc -std=gnu99 supports -Wmissing-format-attribute... yes', # 11
'checking if gcc -std=gnu99 supports -Werror... yes', # 11
'checking if gcc -std=gnu99 supports -Werror=attributes... yes', # 11
'checking if gcc -std=gnu99 supports -Wbad-function-cast... yes', # 11
'checking if gcc -std=gnu99 supports -pedantic... yes', # 11
'checking for wint_t... yes', # 11
'checking for wchar_t... yes', # 11
'checking for unsigned long long int... yes', # 11
'checking for unsetenv... yes', # 11
'checking for sys/un.h... yes', # 11
'checking for sysconf... yes', # 11
'checking for stddef.h... yes', # 11
'checking for snprintf... (cached) yes', # 11
'checking for sigaction... yes', # 11
'checking for select... yes', # 11
'checking for ranlib... (cached) ranlib', # 11
'checking for putenv... yes', # 11
'checking for iconv... yes', # 11
'checking for geteuid... yes', # 11
'checking for dlopen... no', # 11
'checking errno.h usability... yes', # 11
'checking errno.h presence... yes', # 11
'checking dirent.h usability... yes', # 11
'checking dirent.h presence... yes', # 11
'checking whether gcc and cc understand -c and -o together... yes', # 10
'checking target system type... i686-pc-linux-gnu', # 10
'checking sys/un.h usability... yes', # 10
'checking sys/un.h presence... yes', # 10
'checking sys/ioctl.h usability... yes', # 10
'checking sys/ioctl.h presence... yes', # 10
);

my @compiled;

## compile strings into regular expressions so we can do ~~ match
foreach (@lines)
{
    my $quoted = quotemeta($_);
    push (@compiled, qr/^$quoted$/);
}

while (<>) {
	next if ($_ ~~ @compiled);

	print;
}

