#!/bin/bash

OURNAME=`basename -- $0`
TARDIR="$HOME/.cache/norm"
LIBSUFFIX=so
[[ $OSTYPE == *darwin* ]] && LIBSUFFIX=dylib

COMPILEDIR="$DEFAULT_PREFIX/tmp/compile"
NUMCPU=`getconf _NPROCESSORS_ONLN`
[ -z "$NUMCPU" ] && NUMCPU=1
NUMJOBS=$(( $NUMCPU * 2 ))

## find shasum binary
SHASUM_BIN=shasum
hash $SHASUM_BIN 2>/dev/null || SHASUM_BIN=sha1sum

## get machine id for later
MACHINEID="$HOSTNAME.${BASH_VERSINFO[5]}"
[ -z "${debian_chroot:-}" -a -r /etc/debian_chroot ] && debian_chroot=$(cat /etc/debian_chroot)
[ -n "$debian_chroot" ] && MACHINEID+=".$debian_chroot"

. "$NORMDIR"/norm_common.functions
. "$NORMDIR"/norm_common.prefix

onerror() {
    log "Package $FORMULA failed to build"
}

onexit() {
    for line in "${CAVEATS[@]}"; do log $line; done
    log "Exiting"
}

setup_traps() {
    set -eE
    set -o pipefail
    trap onerror ERR
    trap onexit EXIT
}

log() {
    local DATE=`LANG=C date '+%d/%b/%Y:%T %z'`
    echo "[$DATE] [norm] $@"
}

log_success() {
    log "Package $FORMULA -- success"
}

