workspace:
   base: /build
   path: norm

pipeline:
  ${FORMULA}:
    image: normdebian
    commands:
    - ./norm-testall ${FORMULA}
    volumes:
    - /var/cache/norm/testlogs:/build/norm/testlogs
    - /var/cache/norm/ccache:/root/.cache/ccache

depends_on:
- normdebian

matrix:
  FORMULA:
  - aria2
  - atomicparsley
  - autoconf
  - automake
  - bash-completion
  - bento4
  - bison
  - bloaty
  - brotli
  - bzip2
  - ccache
  - cmake
  - cpuid
  - curl
  - dnsperf
  - ent
  - exiftool
  - ffmpeg
  - file
  - flac
  - flex
  - fswatch
  - gcc
  - gcc-10.1
  - gcc-10.2
  - gcc-11.1
  - gcc-11.2
  - gcc-11.3
  - gcc-12.1
  - gcc-12.2
  - gcc-9.3
  - gettext
  - git
  - glib
  - go
  - gperf
  - gpg
  - graphicsmagick
  - graphviz
  - gsed
  - gzip
  - hashcat
  - imagemagick
  - jo
  - john
  - jq
  - knot
  - lame
  - lepton
  - leveldb
  - libacl
  - libarchive
  - libasound
  - libassuan
  - libattr
  - libboost
  - libbsd
  - libcapstone
  - libcares
  - libck
  - libdav1d
  - libdb
  - libde265
  - libdrm
  - libedit
  - libevent
  - libexif
  - libexpat
  - libfdk-aac
  - libffi
  - libgcrypt
  - libgdbm
  - libgif
  - libgmp
  - libgnutls
  - libgpg-error
  - libheif
  - libicu
  - libidn
  - libidn2
  - libisl
  - libjasper
  - libjbig
  - libjpeg
  - libksba
  - liblcms2
  - liblmdb
  - liblz4
  - liblzo
  - libmd
  - libmount
  - libmpc
  - libmpdec
  - libmpfr
  - libncurses
  - libnettle
  - libnghttp2
  - libnpth
  - libogg
  - libonig
  - libopus
  - libopusenc
  - libopusfile
  - libp11-kit
  - libpciaccess
  - libpcre
  - libpcre2
  - libpng
  - libprotobuf
  - libpsl
  - libpthread-stubs
  - libraw
  - libre2
  - libreadline
  - librhash
  - libsdl
  - libsdl2
  - libsdl3
  - libseccomp
  - libslang
  - libsrt
  - libsvt-hevc
  - libsvtav1
  - libtasn1
  - libtiff
  - libtirpc
  - libtool
  - libtorrent
  - libunistring
  - liburcu
  - libuuid
  - libuv
  - libvips
  - libvorbis
  - libvpx
  - libwebp
  - libxml
  - libxxhash
  - lrzip
  - m4
  - make
  - mc
  - mediainfo
  - memcached
  - meson
  - moreutils
  - nasm
  - nginx
  - ninja
  - node
  - opencv2
  - openssh
  - openssl
  - opus-tools
  - p7zip
  - par2
  - patch
  - patchutils
  - perl
  - pigz
  - pinentry
  - pixman
  - pkg-config
  - postgresql
  - procps
  - python
  - python2
  - qemu
  - queryperf
  - rsync
  - sox
  - sqlite3
  - squashfs-tools
  - tarantool
  - unzip
  - util-linux
  - valgrind
  - watch
  - wget
  - wget2
  - wrk
  - wrk2
  - x264
  - x265
  - xz
  - yasm
  - zlib
  - zstd
  - zzuf
